Add color to validation output

diff --git a/.test/task2/validate b/.test/task2/validate
--- a/.test/task2/validate
+++ b/.test/task2/validate
@@ -39,7 +39,7 @@ function test_solution() {
     echo "$ACTUAL"
     fail
   fi
-  diff -U 1000 <(tac "$DATA") <(echo "$ACTUAL") || fail 
+  diff --color=always -U 1000 <(tac "$DATA") <(echo "$ACTUAL") || fail 
 }
 
 
diff --git a/.test/task4/validate b/.test/task4/validate
--- a/.test/task4/validate
+++ b/.test/task4/validate
@@ -36,7 +36,7 @@ function test_solution() {
     echo "$ACTUAL"
     fail "$@"
   fi
-  diff -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail "$@"
+  diff --color=always -U 1000 <(echo "$EXPECTED") <(echo "$ACTUAL") || fail "$@"
 }
 
 
